baseurl = "https://blog.synapsegarden.net"
GoogleAnalytics = "UA-49714021-1"
disqusShortname = "sg-hugo-blog"
languageCode = "en-us"
title = "SynapseGarden Weblog"
theme = "redlounge"
copyright = "Bodie Solomon"

[Author]
	name = "Bodie Solomon"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[[menu.main]]
	name = "Core"
	url = "/core"

[[menu.main]]
	name = "Dev"
	url = "/dev"

[[menu.social]]
	pre = "<i class='fa fa-github'></i>"
	url = "https://github.com/synapse-garden"
	identifier = "github"

[[menu.social]]
	pre = "<i class='fa fa-twitter'></i>"
	url = "https://twitter.com/synapsegarden"
	identifier = "twitter"

[[menu.social]]
	pre = "<i class='fa fa-google-plus'></i>"
	url = "https://plus.google.com/101925672692033800285"
	identifier = "google-plus"

[[menu.footer]]
	name = "SG Weblog Source"
	url = "https://github.com/synapse-garden/blog"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	sidebartitle = "SG"
	sidebartagline = "2016"
	description = "The current affairs of SG."
	twitter = "https://twitter.com/synapsegarden"
	github = "https://github.com/synapse-garden"
	gplus = "https://plus.google.com/+BodieSolomon"
	Copyright = "2015 SynapseGarden."
